# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/miuicamera-amber/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/miuicamera-amber

PRODUCT_COPY_FILES += \
    vendor/xiaomi/miuicamera-amber/proprietary/system/etc/public.libraries-xiaomi.txt:$(TARGET_COPY_OUT_SYSTEM)/etc/public.libraries-xiaomi.txt

PRODUCT_PACKAGES += \
    libcamera_algoup_jni.xiaomi \
    libcamera_ispinterface_jni.xiaomi \
    libcamera_mianode_jni.xiaomi \
    libmtkisp_metadata_sys \
    vendor.mediatek.hardware.camera.isphal-V1-ndk \
    vendor.mediatek.hardware.camera.isphal@1.0_system \
    MiuiCamera
